services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: nutrition_mssql
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your_password123"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      - ./database/schema_sqlserver.sql:/scripts/01-schema.sql
    command: /opt/mssql/bin/sqlservr

volumes:
  mssql_data:
